# Generated manually for Korook admin platform

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("listings", "0012_listing_admin_business_fields"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="UserPlatformProfile",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("role", models.CharField(choices=[("user", "User"), ("business_owner", "Business owner"), ("organizer", "Organizer"), ("moderator", "Moderator"), ("admin", "Admin")], db_index=True, default="user", max_length=32)),
                ("account_status", models.CharField(choices=[("active", "Active"), ("suspended", "Suspended"), ("deleted", "Deleted"), ("pending_review", "Pending review")], db_index=True, default="active", max_length=32)),
                ("admin_note", models.TextField(blank=True, default="")),
                ("suspended_at", models.DateTimeField(blank=True, null=True)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("suspended_by", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="suspensions_issued", to=settings.AUTH_USER_MODEL)),
                ("user", models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name="platform_profile", to=settings.AUTH_USER_MODEL)),
            ],
            options={"verbose_name": "user platform profile", "verbose_name_plural": "user platform profiles"},
        ),
        migrations.CreateModel(
            name="Event",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("title", models.CharField(max_length=255)),
                ("description", models.TextField(blank=True, default="")),
                ("category", models.CharField(blank=True, default="", max_length=100)),
                ("starts_at", models.DateTimeField(db_index=True)),
                ("ends_at", models.DateTimeField(blank=True, null=True)),
                ("location", models.CharField(blank=True, default="", max_length=255)),
                ("address", models.CharField(blank=True, default="", max_length=255)),
                ("city", models.CharField(blank=True, default="", max_length=100)),
                ("state", models.CharField(blank=True, default="", max_length=100)),
                ("zip_code", models.CharField(blank=True, default="", max_length=20)),
                ("country", models.CharField(blank=True, default="", max_length=100)),
                ("latitude", models.FloatField(blank=True, null=True)),
                ("longitude", models.FloatField(blank=True, null=True)),
                ("organizer", models.CharField(blank=True, default="", max_length=255)),
                ("ticket_url", models.URLField(blank=True, default="")),
                ("ticket_provider_label", models.CharField(blank=True, default="", max_length=100)),
                ("status", models.CharField(choices=[("draft", "Draft"), ("published", "Published"), ("hidden", "Hidden")], db_index=True, default="draft", max_length=20)),
                ("is_featured", models.BooleanField(db_index=True, default=False)),
                ("is_sponsored", models.BooleanField(default=False)),
                ("display_priority", models.PositiveIntegerField(db_index=True, default=0)),
                ("cover_image", models.ImageField(blank=True, null=True, upload_to="events/covers/")),
                ("cover_media_status", models.CharField(choices=[("active", "Active"), ("hidden", "Hidden"), ("pending_review", "Pending review"), ("rejected", "Rejected")], default="active", max_length=20)),
                ("cover_moderation_reason", models.CharField(blank=True, default="", max_length=255)),
                ("cover_reviewed_at", models.DateTimeField(blank=True, null=True)),
                ("admin_note", models.TextField(blank=True, default="")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("cover_reviewed_by", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="event_cover_reviews", to=settings.AUTH_USER_MODEL)),
                ("listing", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="events", to="listings.listing")),
                ("owner", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="owned_events", to=settings.AUTH_USER_MODEL)),
            ],
            options={"ordering": ["-starts_at"]},
        ),
        migrations.CreateModel(
            name="Promotion",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("advertiser_name", models.CharField(max_length=255)),
                ("placement", models.CharField(choices=[("home_hero", "Home hero"), ("explore_hero", "Explore hero"), ("business_featured", "Business featured"), ("event_featured", "Event featured"), ("sponsored_card", "Sponsored card")], db_index=True, max_length=32)),
                ("title", models.CharField(max_length=255)),
                ("subtitle", models.CharField(blank=True, default="", max_length=500)),
                ("image", models.ImageField(blank=True, null=True, upload_to="promotions/")),
                ("video_url", models.URLField(blank=True, default="")),
                ("cta_text", models.CharField(blank=True, default="", max_length=100)),
                ("cta_link", models.URLField(blank=True, default="")),
                ("target_route", models.CharField(blank=True, default="", max_length=255)),
                ("target_id", models.CharField(blank=True, default="", max_length=64)),
                ("channel", models.CharField(blank=True, default="", max_length=64)),
                ("starts_at", models.DateTimeField(blank=True, db_index=True, null=True)),
                ("ends_at", models.DateTimeField(blank=True, db_index=True, null=True)),
                ("is_active", models.BooleanField(db_index=True, default=True)),
                ("display_priority", models.PositiveIntegerField(db_index=True, default=0)),
                ("sponsored_label", models.CharField(blank=True, default="", max_length=100)),
                ("status", models.CharField(choices=[("draft", "Draft"), ("scheduled", "Scheduled"), ("active", "Active"), ("expired", "Expired"), ("paused", "Paused")], db_index=True, default="draft", max_length=20)),
                ("hero_approved", models.BooleanField(default=False)),
                ("admin_note", models.TextField(blank=True, default="")),
                ("billing_reference", models.CharField(blank=True, default="", max_length=128)),
                ("campaign_id", models.CharField(blank=True, default="", max_length=128)),
                ("impression_cap", models.PositiveIntegerField(blank=True, null=True)),
                ("budget_cents", models.PositiveIntegerField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("event", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="promotions", to="korook_platform.event")),
                ("listing", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="promotions", to="listings.listing")),
            ],
            options={"ordering": ["display_priority", "-created_at"]},
        ),
        migrations.CreateModel(
            name="BusinessClaim",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("status", models.CharField(choices=[("pending", "Pending"), ("approved", "Approved"), ("rejected", "Rejected")], db_index=True, default="pending", max_length=20)),
                ("admin_note", models.TextField(blank=True, default="")),
                ("reviewed_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("listing", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="claims", to="listings.listing")),
                ("requester", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="business_claims", to=settings.AUTH_USER_MODEL)),
                ("reviewed_by", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="claims_reviewed", to=settings.AUTH_USER_MODEL)),
            ],
            options={"ordering": ["-created_at"]},
        ),
        migrations.CreateModel(
            name="ContentReport",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("reported_object_type", models.CharField(choices=[("user", "User"), ("listing", "Listing"), ("event", "Event"), ("listing_image", "Listing image"), ("promotion", "Promotion")], db_index=True, max_length=32)),
                ("reported_object_id", models.PositiveIntegerField(db_index=True)),
                ("reason", models.CharField(max_length=100)),
                ("description", models.TextField(blank=True, default="")),
                ("status", models.CharField(choices=[("new", "New"), ("in_review", "In review"), ("actioned", "Actioned"), ("dismissed", "Dismissed")], db_index=True, default="new", max_length=20)),
                ("reviewed_at", models.DateTimeField(blank=True, null=True)),
                ("admin_note", models.TextField(blank=True, default="")),
                ("action_taken", models.CharField(choices=[("none", "None"), ("hide", "Hide"), ("delete", "Delete"), ("suspend_user", "Suspend user"), ("restore", "Restore")], default="none", max_length=32)),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("event", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="content_reports", to="korook_platform.event")),
                ("listing", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="content_reports", to="listings.listing")),
                ("listing_image", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="content_reports", to="listings.listingimage")),
                ("reported_by", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="reports_filed", to=settings.AUTH_USER_MODEL)),
                ("reported_user", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name="reports_against", to=settings.AUTH_USER_MODEL)),
                ("reviewed_by", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="reports_reviewed", to=settings.AUTH_USER_MODEL)),
            ],
            options={"ordering": ["-created_at"]},
        ),
        migrations.CreateModel(
            name="AdminAuditLog",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("action_type", models.CharField(db_index=True, max_length=64)),
                ("object_type", models.CharField(db_index=True, max_length=64)),
                ("object_id", models.PositiveIntegerField(db_index=True)),
                ("summary", models.CharField(max_length=500)),
                ("before_state", models.JSONField(blank=True, null=True)),
                ("after_state", models.JSONField(blank=True, null=True)),
                ("admin_note", models.TextField(blank=True, default="")),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("actor", models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="admin_audit_actions", to=settings.AUTH_USER_MODEL)),
            ],
            options={"ordering": ["-created_at"]},
        ),
    ]
