"""
Django settings for iranapp project.

Generated by 'django-admin startproject' using Django 5.2.8.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""
import os
import dj_database_url
from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-wf&#7cpn6(-e@&833ph!0kjg0mgm(ylur9u71b22ta2f89vzc9'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = [
    "community-app-backend-production.up.railway.app",
    "community-app-backend-staging.up.railway.app",
    "api.korook.com",
    "localhost",
    "127.0.0.1",
]

CSRF_TRUSTED_ORIGINS = [
    "https://community-app-backend-production.up.railway.app",
    "https://api.korook.com",
]

CORS_ALLOWED_ORIGINS = [
    "https://korook.com",
    "https://www.korook.com",
    "http://localhost:3000",
    "http://127.0.0.1:3000",
]


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'corsheaders',
    'core',
    'rest_framework',
    'rest_framework_simplejwt',
    'listings',
    'accounts',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'corsheaders.middleware.CorsMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'iranapp.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'iranapp.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASES = {
    "default": dj_database_url.config(
        default=f"sqlite:///{BASE_DIR / 'db.sqlite3'}",
        conn_max_age=600
    )
}


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = 'static/'

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'
REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': (
        'rest_framework_simplejwt.authentication.JWTAuthentication',
    ),
}

# Email — SendGrid Web API for password reset when configured; console for local dev.
_sendgrid_api_key = os.environ.get("SENDGRID_API_KEY", "").strip()
_email_provider = os.environ.get("EMAIL_PROVIDER", "").strip().lower()
DEFAULT_FROM_EMAIL = os.environ.get("DEFAULT_FROM_EMAIL", "noreply@iranianapp.com")

USE_SENDGRID_WEB_API = _email_provider == "sendgrid" and bool(_sendgrid_api_key)
SENDGRID_API_KEY = _sendgrid_api_key if USE_SENDGRID_WEB_API else ""

EMAIL_BACKEND = os.environ.get(
    "EMAIL_BACKEND",
    "django.core.mail.backends.console.EmailBackend",
)

if USE_SENDGRID_WEB_API:
    _active_email_backend = "sendgrid-web-api"
elif _email_provider == "sendgrid":
    _active_email_backend = "console (SENDGRID_API_KEY missing)"
    print(
        "[email] EMAIL_PROVIDER=sendgrid but SENDGRID_API_KEY is not set; "
        "using console backend"
    )
elif "smtp" in EMAIL_BACKEND.lower():
    _active_email_backend = "smtp"
else:
    _active_email_backend = "console"

print(f"[email] Active email backend: {_active_email_backend}")

# Frontend page that collects uid + token and submits the new password.
FRONTEND_PASSWORD_RESET_URL = os.environ.get(
    'FRONTEND_PASSWORD_RESET_URL',
    'http://localhost:3000/reset-password',
)

# Frontend page that verifies email from uid + token query params.
FRONTEND_EMAIL_VERIFICATION_URL = os.environ.get(
    'FRONTEND_EMAIL_VERIFICATION_URL',
    'https://korook.com/verify-email',
)

MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / 'media'