# Generated by Django 5.2.8 on 2025-12-05 03:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='package',
            name='max_listings',
        ),
        migrations.AddField(
            model_name='package',
            name='description',
            field=models.TextField(blank=True),
        ),
    ]
