# Generated by Django 5.2.8 on 2025-12-05 03:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0002_remove_package_max_listings_package_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
