# Generated by Django 5.2.8 on 2025-12-12 20:03

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0004_delete_package_alter_listing_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='listingimage',
            name='uploaded_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
