# Generated by Django 5.2.8 on 2025-12-12 20:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0005_listingimage_uploaded_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listingimage',
            name='image',
            field=models.ImageField(upload_to='listings/'),
        ),
    ]
