# Generated by Django 6.0.6 on 2026-10-05 22:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0013_listing_subscription_billing_fields'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='listing',
            new_name='listings_li_city_1091e3_idx',
            old_name='listings_li_city_0bb1d0_idx',
        ),
        migrations.AlterField(
            model_name='listing',
            name='is_featured',
            field=models.BooleanField(db_index=True, default=False),
        ),
    ]
